#!/usr/bin/env ruby
# Derived from http://errtheblog.com/posts/89-huba-huba

home = File.expand_path('~')
dotfiles = File.expand_path('active')
Dir.new(dotfiles).each do |file|
  next if file =~ /(\.|\.\.)/
  begin
  target = File.join(home, ".#{file}")
  if File.symlink? target
      File.unlink(target)
      puts "Old link to .#{file} exists. Unlinking existing .#{file}"
  elsif File.exists? target
      File.rename(target, target + '.backup')
      puts ".#{file} exists. Backup existing .#{file} as .#{file}.backup"
  end
  File.symlink(File.join(dotfiles, file), target)
  puts "Installed .#{file}"
  rescue Exception => e
    puts "Failed to install .#{file}. Reason: #{e.message}"
  end
end