#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
trap "rm -f .git/tags.$$" EXIT
if [[ -s /usr/local/bin/ctags ]] ; then
	ctags --tag-relative -Rf.git/tags.$$ --exclude=.git --languages=-javascript,sql
	mv .git/tags.$$ .git/tags
fi

